version: 2

references:
    fetch_source: &fetch_source
        checkout

    getting_py_version: &getting_py_version
        run:
            name: Get Python version
            command: python --version

    installing_dependencies: &installing_dependencies
        run:
            name: Installing Dependencies
            command: sudo pip install -r requirements.txt

    save_repo_cache: &save_repo_cache
        save_cache:
                paths: venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}

    saving_artifacts: &saving_artifacts
        store_artifacts:
            path: build
jobs:
    running_flask:
        docker:
            - image: circleci/python:3.6.1
        working_directory: ~/flask-app
        restore_cache:
            keys: v1-dependencies-{{ checksum "requirements.txt" }}
        steps:
            - *fetch_source
            - *getting_py_version
            - *installing_dependencies
            - *save_repo_cache

workflows:
    version: 2
    flask_app:
        jobs:
            - running_flask