version: 2

jobs:
    running_flask:
        docker:
            - image: circleci/python:3.6.1
        working_directory: ~/flask-app
        restore_cache:
            keys: v1-dependencies-{{ checksum "requirements.txt" }}
        steps:
            - checkout
            - run:
                name: Get Python version
                command: python --version
            - run:
                name: Installing Dependencies
                command: sudo pip install -r requirements.txt
            - save_cache:
                paths: venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}


workflows:
    version: 2
    flask_app:
        jobs:
            - running_flask